# includes diagnostic sensors
<<: !include sensor-config.yaml

# external_components:
#   - source: github://echavet/MitsubishiCN105ESPHome
#     refresh: 0s
external_components:
 - source:
     type: local
     path: ../components 

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO1
  rx_pin: GPIO2
  #debug:
    

climate:
  - platform: cn105
    name: ${clim_name}
    icon: mdi:heat-pump
    id: "atoms3_clim"
    uart_id: HP_UART
    visual:
      min_temperature: 17
      max_temperature: 28
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1
    compressor_frequency_sensor:
      name: Compressor frequency
    input_power_sensor:
      name: Input power
    vertical_vane_select:
      name: Vertical vane orientation
    #horizontal_vane_select:
    #  name: Orientation de la Vane Horizontale
    #isee_sensor:
    #  name: ISEE Sensor
    remote_temperature_timeout: 60min
    update_interval: 3500ms # shouldn't be less than 1 second
    debounce_delay: 100ms # delay to prevent bouncing
    hp_uptime_connection_sensor:
      name: ${name} uptime Connection
      update_interval: 30s
    supports:
      mode: [COOL, HEAT, FAN_ONLY, DRY]
      fan_mode: [AUTO, QUIET, LOW, MEDIUM, HIGH]
      swing_mode: ["OFF", VERTICAL]
      dual_setpoint: false
    outside_air_temperature_sensor:
      name: ${name} Outdoor air temperature
    runtime_hours_sensor:
      name: Runtime hours
    kwh_sensor:
      name: Energy consumed
    input_power_sensor:
      name: Input power
    stage_sensor:
      name: Stage
    sub_mode_sensor:
      name: Sub mode
    auto_sub_mode_sensor:
      name: Auto sub mode
